// packages/phone-mask-svelte/src/components/PhoneInput.svelte
<script lang="ts">
  import { tick } from 'svelte';
  import { useCountry } from '../composables/internal/useCountry.svelte';
  import { useFormatter } from '../composables/internal/useFormatter.svelte';
  import { useValidationHint } from '../composables/internal/useValidationHint.svelte';
  import { useInputHandlers } from '../composables/internal/useInputHandlers.svelte';
  import { useCountrySelector } from '../composables/internal/useCountrySelector.svelte';
  import { useCopyAction } from '../composables/internal/useCopyAction.svelte';
  import { useTheme } from '../composables/internal/useTheme.svelte';

  import type { PhoneInputProps } from '../types';

  let {
    value = $bindable(''),
    country: propCountry,
    detect = true,
    locale: propLocale,
    size = 'normal',
    theme = 'auto',
    disabled = false,
    readonly = false,
    showCopy = true,
    showClear = false,
    withValidity = true,
    searchPlaceholder = 'Search country or code...',
    noResultsText = 'No countries found',
    clearButtonLabel = 'Clear phone number',
    dropdownClass = '',
    disableDefaultStyles = false,
    onchange,
    oncountrychange,
    onvalidationchange,
    onfocus,
    onblur,
    oncopy,
    onclear,
    flag,
    copysvg,
    clearsvg,
    actionsbefore,
    class: extraClass,
    ...restProps
  }: PhoneInputProps = $props();

  // --- Refs ---
  let rootEl = $state<HTMLDivElement | null>(null);
  let telEl = $state<HTMLInputElement | null>(null);
  let liveEl = $state<HTMLDivElement | null>(null);
  let dropdownEl = $state<HTMLDivElement | null>(null);
  let searchEl = $state<HTMLInputElement | null>(null);
  let selectorEl = $state<HTMLDivElement | null>(null);

  // --- Composables (keep as objects to preserve reactive getter chains) ---
  const countryData = useCountry({
    country: () => propCountry,
    locale: () => propLocale,
    detect: () => detect,
    onCountryChange: (...args) => oncountrychange?.(...args)
  });

  const formatterData = useFormatter({
    country: () => countryData.country,
    value: () => value,
    onChange: (v) => (value = v),
    onPhoneChange: (...args) => onchange?.(...args),
    onValidationChange: (...args) => onvalidationchange?.(...args)
  });

  const validationHint = useValidationHint();

  const inactive = $derived(disabled || readonly);
  const incomplete = $derived(validationHint.showValidationHint && formatterData.shouldShowWarn);
  const showCopyButton = $derived(showCopy && !formatterData.isEmpty && !disabled);
  const showClearButton = $derived(showClear && !formatterData.isEmpty && !inactive);

  const copyData = useCopyAction({
    liveRef: () => liveEl,
    fullFormatted: () => formatterData.fullFormatted,
    onCopy: (...args) => oncopy?.(...args)
  });

  const focusInput = () => tick().then(() => telEl?.focus());

  const selectorData = useCountrySelector({
    rootRef: () => rootEl,
    dropdownRef: () => dropdownEl,
    searchRef: () => searchEl,
    selectorRef: () => selectorEl,
    locale: () => countryData.locale,
    countryOption: () => propCountry,
    inactive: () => inactive,
    onSelectCountry: countryData.setCountry,
    onAfterSelect: focusInput
  });

  const inputHandlers = useInputHandlers({
    formatter: () => formatterData.formatter,
    digits: () => formatterData.digits,
    inactive: () => inactive,
    onChange: (v) => (value = v),
    scheduleValidationHint: validationHint.scheduleValidationHint
  });

  const handleFocus = (e: FocusEvent) => {
    validationHint.clearValidationHint(false);
    selectorData.closeDropdown();
    onfocus?.(e);
  };

  const handleBlur = (e: FocusEvent) => onblur?.(e);

  export function focus() { focusInput(); }
  export function blur() { telEl?.blur(); }
  export function clear() {
    value = '';
    validationHint.clearValidationHint();
    onclear?.();
  }
  export function selectCountry(code?: string | null) { countryData.setCountry(code); }
  export function getFullNumber() { return formatterData.full; }
  export function getFullFormattedNumber() { return formatterData.fullFormatted; }
  export function getDigits() { return formatterData.digits; }
  export function isValid() { return formatterData.isComplete; }
  export function isComplete() { return formatterData.isComplete; }

  const handleClearClick = () => { clear(); focusInput(); };

  const themeData = useTheme({
    theme: () => theme,
  });

  const rootClasses = $derived(
    ['phone-input', `size-${size}`, themeData.themeClass,
      disabled && 'is-disabled',
      readonly && 'is-readonly',
      disableDefaultStyles && 'is-unstyled',
      withValidity && incomplete && 'is-incomplete',
      withValidity && formatterData.isComplete && 'is-complete',
      extraClass
    ].filter(Boolean).join(' ')
  );

  const actionsCount = $derived(+showCopyButton + +showClearButton + (actionsbefore ? 1 : 0));

  // Portal action — appends dropdown to document.body
  function portal(node: HTMLElement) {
    document.body.appendChild(node);
    return { destroy: () => node.remove() };
  }
</script>

<div bind:this={rootEl} class={rootClasses} {...restProps}
  style:--pi-actions-count={actionsCount}
  role="group" aria-label="Phone input with country selector">

  <!-- Country Selector -->
  <div bind:this={selectorEl} class="pi-selector">
    <button type="button"
      class="pi-selector-btn"
      class:no-dropdown={!selectorData.hasDropdown || readonly}
      {disabled}
      tabindex={inactive || !selectorData.hasDropdown ? -1 : undefined}
      aria-label="Selected country: {countryData.country.name}"
      aria-expanded={selectorData.dropdownOpen}
      aria-haspopup={selectorData.hasDropdown ? 'listbox' : undefined}
      onclick={selectorData.toggleDropdown}>
      <span class="pi-flag" role="img" aria-label="{countryData.country.name} flag">
        {#if flag}{@render flag(countryData.country)}{:else}{countryData.country.flag}{/if}
      </span>
      <span class="pi-code">{countryData.country.code}</span>
      {#if !inactive && selectorData.hasDropdown}
        <svg class="pi-chevron" class:is-open={selectorData.dropdownOpen}
          width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true">
          <path d="M2.5 4.5L6 8L9.5 4.5" stroke="currentColor"
            stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      {/if}
    </button>
  </div>

  <!-- Input -->
  <div class="pi-input-wrap">
    <input bind:this={telEl} type="tel" inputmode="tel"
      autocomplete="tel-national" autocorrect="off"
      autocapitalize="off" spellcheck="false"
      class="pi-input"
      placeholder={formatterData.displayPlaceholder}
      value={formatterData.displayValue}
      {disabled} readonly={readonly}
      aria-invalid={incomplete}
      onbeforeinput={inputHandlers.handleBeforeInput}
      oninput={inputHandlers.handleInput}
      onkeydown={inputHandlers.handleKeydown}
      onpaste={inputHandlers.handlePaste}
      onfocus={handleFocus}
      onblur={handleBlur} />

    <!-- Actions -->
    <div class="pi-actions" role="toolbar" aria-label="Phone input actions">
      {#if actionsbefore}
        {@render actionsbefore()}
      {/if}

      {#if showCopyButton}
        <button type="button"
          class="pi-btn pi-btn-copy" class:is-copied={copyData.copied}
          aria-label={copyData.copyAriaLabel} title={copyData.copyButtonTitle}
          onclick={copyData.onCopyClick}>
          {#if copysvg}
            {@render copysvg(copyData.copied)}
          {:else if copyData.copied}
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
              <path d="M6.5 11.5L3 8L4.06 6.94L6.5 9.38L11.94 3.94L13 5L6.5 11.5Z" fill="currentColor"/>
            </svg>
          {:else}
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
              <path d="M13.5 5.5V13.5H5.5V5.5H13.5ZM13.5 4H5.5C4.67 4 4 4.67 4 5.5V13.5C4 14.33 4.67 15 5.5 15H13.5C14.33 15 15 14.33 15 13.5V5.5C15 4.67 14.33 4 13.5 4ZM10.5 1H2.5V11H4V2.5H10.5V1Z" fill="currentColor"/>
            </svg>
          {/if}
        </button>
      {/if}

      {#if showClearButton}
        <button type="button"
          class="pi-btn pi-btn-clear"
          aria-label={clearButtonLabel} title={clearButtonLabel}
          onclick={handleClearClick}>
          {#if clearsvg}
            {@render clearsvg()}
          {:else}
            <svg width="11" height="11" viewBox="0 0 14 14" fill="none" aria-hidden="true">
              <path d="M14 1.41L12.59 0L7 5.59L1.41 0L0 1.41L5.59 7L0 12.59L1.41 14L7 8.41L12.59 14L14 12.59L8.41 7L14 1.41Z" fill="currentColor"/>
            </svg>
          {/if}
        </button>
      {/if}
    </div>
  </div>
</div>

<!-- Dropdown — portaled to body -->
{#if selectorData.dropdownOpen}
  <div use:portal bind:this={dropdownEl}
    class="phone-dropdown {dropdownClass} {themeData.themeClass}"
    class:is-closing={selectorData.isClosing}
    style:position="absolute"
    style:top={selectorData.dropdownStyle.top}
    style:left={selectorData.dropdownStyle.left}
    style:width={selectorData.dropdownStyle.width}
    role="dialog" aria-modal="false" aria-label="Select country"
    onanimationend={selectorData.handleDropdownAnimationEnd}>
    <div class="pi-search-wrap">
      <input bind:this={searchEl} type="search" class="pi-search"
        aria-label="Search countries" placeholder={searchPlaceholder}
        value={selectorData.search}
        onkeydown={selectorData.handleSearchKeydown}
        oninput={selectorData.handleSearchChange} />
    </div>
    <ul class="pi-options" role="listbox"
      aria-activedescendant="option-{selectorData.focusedIndex}" tabindex="-1">
      {#each selectorData.filteredCountries as c, idx (c.id)}
        <li id="option-{idx}" role="option"
          class="pi-option"
          class:is-focused={idx === selectorData.focusedIndex}
          class:is-selected={c.id === countryData.country.id}
          aria-selected={c.id === countryData.country.id}
          title={c.name}
          onclick={() => selectorData.selectCountry(c.id)}
          onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); selectorData.selectCountry(c.id); } }}
          onmouseenter={() => selectorData.setFocusedIndex(idx)}>
          <span class="pi-flag" role="img" aria-label="{c.name} flag">
            {#if flag}{@render flag(c)}{:else}{c.flag}{/if}
          </span>
          <span class="pi-opt-name">{c.name}</span>
          <span class="pi-opt-code">{c.code}</span>
        </li>
      {:else}
        <li class="pi-empty">{noResultsText}</li>
      {/each}
    </ul>
  </div>
{/if}

<!-- Screen reader live region -->
<div bind:this={liveEl} class="sr-only" role="status" aria-live="polite" aria-atomic="true"></div>

// packages/phone-mask-react/src/components/PhoneInput.tsx
import React, { useImperativeHandle, useRef, useCallback, useMemo, type CSSProperties, type Ref } from 'react';
import { createPortal } from 'react-dom';
import { useFormatter } from '../hooks/internal/useFormatter';
import { useCountry } from '../hooks/internal/useCountry';
import { useValidationHint } from '../hooks/internal/useValidationHint';
import { useInputHandlers } from '../hooks/internal/useInputHandlers';
import { useCountrySelector } from '../hooks/internal/useCountrySelector';
import { useCopyAction } from '../hooks/internal/useCopyAction';

import type { PhoneInputProps, PhoneInputRef } from '../types';

type PhoneInputComponent = PhoneInputProps & { ref?: Ref<PhoneInputRef> };

export const PhoneInput = ({ ref, ...props }: PhoneInputComponent) => {
  const {
    value = '',
    country: propCountry,
    detect = true,
    locale: propLocale,
    size = 'normal',
    theme = 'auto',
    disabled = false,
    readonly = false,
    showCopy = true,
    showClear = false,
    withValidity = true,
    searchPlaceholder = 'Search country or code...',
    noResultsText = 'No countries found',
    clearButtonLabel = 'Clear phone number',
    dropdownClass = '',
    disableDefaultStyles = false,
    onChange,
    onPhoneChange,
    onCountryChange,
    onValidationChange,
    onFocus,
    onBlur,
    onCopy,
    onClear,
    renderActionsBefore,
    renderFlag,
    renderCopySvg,
    renderClearSvg
  } = props;

  const { country, setCountry, locale } = useCountry({
    country: propCountry,
    locale: propLocale,
    detect,
    onCountryChange
  });

  const {
    digits,
    formatter,
    displayPlaceholder,
    displayValue,
    full,
    fullFormatted,
    isComplete,
    isEmpty,
    shouldShowWarn
  } = useFormatter({
    country,
    value,
    onChange,
    onPhoneChange,
    onValidationChange
  });

  const { showValidationHint, clearValidationHint, scheduleValidationHint } = useValidationHint();

  const telRef = useRef<HTMLInputElement>(null);
  const rootRef = useRef<HTMLDivElement>(null);
  const liveRef = useRef<HTMLDivElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const searchRef = useRef<HTMLInputElement>(null);
  const selectorRef = useRef<HTMLDivElement>(null);

  const inactive = disabled || readonly;
  const incomplete = showValidationHint && shouldShowWarn;

  const showCopyButton = showCopy && !isEmpty && !disabled;
  const showClearButton = showClear && !isEmpty && !inactive;

  const {
    copied,
    copyAriaLabel,
    copyButtonTitle,
    onCopyClick: handleCopyClick
  } = useCopyAction({
    liveRef,
    fullFormatted,
    onCopy
  });

  const focusInput = useCallback(() => {
    setTimeout(() => telRef.current?.focus(), 0);
  }, []);

  const { handleBeforeInput, handleInput, handleKeydown, handlePaste } = useInputHandlers({
    formatter,
    digits,
    inactive,
    onChange,
    scheduleValidationHint
  });

  const {
    dropdownOpen,
    isClosing,
    search,
    focusedIndex,
    dropdownStyle,
    filteredCountries,
    hasDropdown,
    closeDropdown,
    toggleDropdown,
    selectCountry,
    setFocusedIndex,
    handleSearchChange,
    handleSearchKeydown,
    handleDropdownAnimationEnd
  } = useCountrySelector({
    rootRef,
    dropdownRef,
    searchRef,
    selectorRef,
    locale,
    inactive,
    countryOption: propCountry,
    onSelectCountry: setCountry,
    onAfterSelect: focusInput
  });

  // Input focus behavior (close dropdown, clear validation timer, and call onFocus callback)
  const handleFocus = useCallback(
    (e: React.FocusEvent<HTMLInputElement>) => {
      clearValidationHint(false);
      closeDropdown();
      onFocus?.(e);
    },
    [onFocus, closeDropdown, clearValidationHint]
  );

  const clear = useCallback(() => {
    onChange?.('');
    clearValidationHint();
    onClear?.();
  }, [onChange, onClear, clearValidationHint]);

  // Clear functionality
  const handleClearClick = useCallback(() => {
    clear();
    focusInput();
  }, [clear, focusInput]);

  // Imperative handle
  useImperativeHandle(
    ref,
    () => ({
      focus: focusInput,
      blur: () => telRef.current?.blur(),
      clear,
      selectCountry,
      getFullNumber: () => full,
      getFullFormattedNumber: () => fullFormatted,
      getDigits: () => digits,
      isValid: () => isComplete,
      isComplete: () => isComplete
    }),
    [focusInput, selectCountry, full, fullFormatted, digits, isComplete, clear]
  );

  // Theme class
  const themeClass = useMemo(() => {
    if (theme !== 'auto') return `theme-${theme}`;
    if (typeof window !== 'undefined' && window.matchMedia?.('(prefers-color-scheme: dark)').matches) {
      return 'theme-dark';
    }
    return 'theme-light';
  }, [theme]);

  const rootClasses = [
    'phone-input',
    `size-${size}`,
    themeClass,
    disabled && 'is-disabled',
    readonly && 'is-readonly',
    disableDefaultStyles && 'is-unstyled',
    withValidity && incomplete && 'is-incomplete',
    withValidity && isComplete && 'is-complete'
  ]
    .filter(Boolean)
    .join(' ');

  const actionsCount = +showCopyButton + +showClearButton + (renderActionsBefore ? 1 : 0);

  return (
    <>
      <div
        ref={rootRef}
        className={rootClasses}
        style={{ '--pi-actions-count': actionsCount } as CSSProperties}
        role="group"
        aria-label="Phone input with country selector"
      >
        {/* Country Selector */}
        <div className="pi-selector" ref={selectorRef}>
          <button
            type="button"
            className={`pi-selector-btn ${!hasDropdown || readonly ? 'no-dropdown' : ''}`}
            disabled={disabled}
            tabIndex={inactive || !hasDropdown ? -1 : undefined}
            aria-label={`Selected country: ${country.name}`}
            aria-expanded={dropdownOpen}
            aria-haspopup={hasDropdown ? 'listbox' : undefined}
            onClick={toggleDropdown}
          >
            <span className="pi-flag" role="img" aria-label={`${country.name} flag`}>
              {renderFlag ? renderFlag(country) : country.flag}
            </span>
            <span className="pi-code">{country.code}</span>
            {!inactive && hasDropdown && (
              <svg
                className={`pi-chevron ${dropdownOpen ? 'is-open' : ''}`}
                width="12"
                height="12"
                viewBox="0 0 12 12"
                fill="none"
                aria-hidden="true"
              >
                <path
                  d="M2.5 4.5L6 8L9.5 4.5"
                  stroke="currentColor"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            )}
          </button>
        </div>

        {/* Input Container */}
        <div className="pi-input-wrap">
          <input
            ref={telRef}
            type="tel"
            inputMode="tel"
            autoComplete="tel-national"
            autoCorrect="off"
            autoCapitalize="off"
            spellCheck={false}
            className="pi-input"
            placeholder={displayPlaceholder}
            value={displayValue}
            disabled={disabled}
            readOnly={readonly}
            aria-invalid={incomplete}
            onInput={handleInput}
            onBeforeInput={handleBeforeInput}
            onKeyDown={handleKeydown}
            onPaste={handlePaste}
            onFocus={handleFocus}
            onBlur={onBlur}
          />

          {/* Action Buttons */}
          <div className="pi-actions" role="toolbar" aria-label="Phone input actions">
            {renderActionsBefore && renderActionsBefore()}

            {showCopyButton && (
              <button
                type="button"
                className={`pi-btn pi-btn-copy ${copied ? 'is-copied' : ''}`}
                aria-label={copyAriaLabel}
                title={copyButtonTitle}
                onClick={handleCopyClick}
              >
                {renderCopySvg ? (
                  renderCopySvg(copied)
                ) : copied ? (
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
                    <path d="M6.5 11.5L3 8L4.06 6.94L6.5 9.38L11.94 3.94L13 5L6.5 11.5Z" fill="currentColor" />
                  </svg>
                ) : (
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
                    <path
                      d="M13.5 5.5V13.5H5.5V5.5H13.5ZM13.5 4H5.5C4.67 4 4 4.67 4 5.5V13.5C4 14.33 4.67 15 5.5 15H13.5C14.33 15 15 14.33 15 13.5V5.5C15 4.67 14.33 4 13.5 4ZM10.5 1H2.5V11H4V2.5H10.5V1Z"
                      fill="currentColor"
                    />
                  </svg>
                )}
              </button>
            )}

            {showClearButton && (
              <button
                type="button"
                className="pi-btn pi-btn-clear"
                aria-label={clearButtonLabel}
                title={clearButtonLabel}
                onClick={handleClearClick}
              >
                {renderClearSvg ? (
                  renderClearSvg()
                ) : (
                  <svg width="11" height="11" viewBox="0 0 14 14" fill="none" aria-hidden="true">
                    <path
                      d="M14 1.41L12.59 0L7 5.59L1.41 0L0 1.41L5.59 7L0 12.59L1.41 14L7 8.41L12.59 14L14 12.59L8.41 7L14 1.41Z"
                      fill="currentColor"
                    />
                  </svg>
                )}
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Dropdown */}
      {dropdownOpen &&
        typeof document !== 'undefined' &&
        createPortal(
          <div
            ref={dropdownRef}
            className={`phone-dropdown ${dropdownClass} ${themeClass} ${isClosing ? 'is-closing' : ''}`}
            style={dropdownStyle}
            role="dialog"
            aria-modal="false"
            aria-label="Select country"
            onAnimationEnd={handleDropdownAnimationEnd}
          >
            <div className="pi-search-wrap">
              <input
                ref={searchRef}
                type="search"
                className="pi-search"
                aria-label="Search countries"
                placeholder={searchPlaceholder}
                value={search}
                onChange={handleSearchChange}
                onKeyDown={handleSearchKeydown}
              />
            </div>
            <ul className="pi-options" role="listbox" aria-activedescendant={`option-${focusedIndex}`} tabIndex={-1}>
              {filteredCountries.length > 0 ? (
                filteredCountries.map((c, idx) => (
                  <li
                    key={c.id}
                    id={`option-${idx}`}
                    role="option"
                    className={`pi-option ${idx === focusedIndex ? 'is-focused' : ''} ${
                      c.id === country.id ? 'is-selected' : ''
                    }`}
                    aria-selected={c.id === country.id}
                    title={c.name}
                    onClick={() => selectCountry(c.id)}
                    onMouseEnter={() => setFocusedIndex(idx)}
                  >
                    <span className="pi-flag" role="img" aria-label={`${c.name} flag`}>
                      {renderFlag ? renderFlag(c) : c.flag}
                    </span>
                    <span className="pi-opt-name">{c.name}</span>
                    <span className="pi-opt-code">{c.code}</span>
                  </li>
                ))
              ) : (
                <li className="pi-empty">{noResultsText}</li>
              )}
            </ul>
          </div>,
          document.body
        )}

      {/* Screen reader announcements */}
      <div ref={liveRef} className="sr-only" role="status" aria-live="polite" aria-atomic="true" />
    </>
  );
};

PhoneInput.displayName = 'PhoneInput';
