// packages/phone-mask-angular/src/phone-input/phone-input.component.ts
import { NgTemplateOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  TemplateRef,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  contentChild,
  effect,
  forwardRef,
  inject,
  input,
  model,
  output,
  signal,
  untracked,
  viewChild
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type { CountryKey, MaskFull } from '@desource/phone-mask';
import { extractDigits } from '@desource/phone-mask/kit';
import { PHONE_MASK_CONFIG } from '../config';
import { optionalBooleanAttribute } from '../internal/boolean-input';
import { UseCopyActionService } from '../services/internal/useCopyAction.service';
import { UseCountryService } from '../services/internal/useCountry.service';
import { UseCountrySelectorService } from '../services/internal/useCountrySelector.service';
import { UseFormatterService } from '../services/internal/useFormatter.service';
import { UseInputHandlersService } from '../services/internal/useInputHandlers.service';
import { UseThemeService } from '../services/internal/useTheme.service';
import { UseValidationHintService } from '../services/internal/useValidationHint.service';
import { UseClipboardService } from '../services/utility/useClipboard.service';
import type { PhoneInputRef, PhoneMaskConfig, PhoneNumber, Size, Theme } from '../types';

let nextDropdownId = 0;

@Component({
  selector: 'desource-phone-input',
  standalone: true,
  imports: [NgTemplateOutlet],
  templateUrl: './phone-input.component.html',
  styleUrl: './phone-input.component.scss',
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    UseClipboardService,
    UseCopyActionService,
    UseCountryService,
    UseCountrySelectorService,
    UseFormatterService,
    UseInputHandlersService,
    UseThemeService,
    UseValidationHintService,
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => PhoneInputComponent),
      multi: true
    }
  ]
})
export class PhoneInputComponent implements ControlValueAccessor, PhoneInputRef {
  readonly value = model<string>('');

  readonly id = input<string | undefined>();
  readonly name = input<string | undefined>();
  readonly countryInput = input<CountryKey | string | undefined>(undefined, { alias: 'country' });
  readonly detectInput = input<boolean | undefined, unknown>(undefined, {
    alias: 'detect',
    transform: optionalBooleanAttribute
  });
  readonly localeInput = input<string | undefined>(undefined, { alias: 'locale' });
  readonly size = input<Size>('normal');
  readonly theme = input<Theme>('auto');
  readonly disabledInput = input(false, { alias: 'disabled', transform: booleanAttribute });
  readonly readOnlyInput = input(false, { alias: 'readonly', transform: booleanAttribute });
  readonly showCopy = input(true, { transform: booleanAttribute });
  readonly showClear = input(false, { transform: booleanAttribute });
  readonly withValidity = input(true, { transform: booleanAttribute });
  readonly searchPlaceholder = input('Search country or code...');
  readonly noResultsText = input('No countries found');
  readonly clearButtonLabel = input('Clear phone number');
  readonly dropdownClass = input('');
  readonly disableDefaultStyles = input(false, { transform: booleanAttribute });

  readonly phoneChange = output<PhoneNumber>();
  readonly countryChange = output<MaskFull>();
  readonly validationChange = output<boolean>();
  readonly focused = output<FocusEvent>({ alias: 'focus' });
  readonly blurred = output<FocusEvent>({ alias: 'blur' });
  readonly copiedValue = output<string>({ alias: 'copy' });
  readonly cleared = output<void>({ alias: 'clear' });

  readonly actionsBeforeTemplate = contentChild<TemplateRef<unknown>>('actionsBefore');
  readonly flagTemplate = contentChild<TemplateRef<{ $implicit: MaskFull; country: MaskFull }>>('flag');
  readonly copySvgTemplate = contentChild<TemplateRef<{ copied: boolean }>>('copySvg');
  readonly clearSvgTemplate = contentChild<TemplateRef<unknown>>('clearSvg');

  private readonly rootRef = viewChild<ElementRef<HTMLDivElement>>('root');
  private readonly telRef = viewChild<ElementRef<HTMLInputElement>>('telInput');
  private readonly liveRef = viewChild<ElementRef<HTMLDivElement>>('live');
  private readonly dropdownRef = viewChild<ElementRef<HTMLDivElement>>('dropdown');
  private readonly searchRef = viewChild<ElementRef<HTMLInputElement>>('searchInput');
  private readonly selectorRef = viewChild<ElementRef<HTMLButtonElement>>('selectorButton');

  private readonly countryState = inject(UseCountryService);
  private readonly formatterState = inject(UseFormatterService);
  private readonly inputHandlers = inject(UseInputHandlersService);
  private readonly validationHint = inject(UseValidationHintService);
  private readonly countrySelector = inject(UseCountrySelectorService);
  private readonly copyAction = inject(UseCopyActionService);
  private readonly themeState = inject(UseThemeService);
  private readonly config: PhoneMaskConfig = inject(PHONE_MASK_CONFIG, { optional: true }) ?? {};

  private readonly formDisabled = signal(false);
  private onTouched: () => void = () => {};
  private onChange: (value: string) => void = () => {};

  readonly locale = this.countryState.locale;
  readonly country = this.countryState.country;
  readonly formatter = this.formatterState.formatter;
  readonly digits = this.formatterState.digits;
  readonly displayPlaceholder = this.formatterState.displayPlaceholder;
  readonly displayValue = this.formatterState.displayValue;
  readonly phoneData = this.formatterState.phoneData;
  readonly full = this.formatterState.full;
  readonly fullFormatted = this.formatterState.fullFormatted;
  readonly isCompleteSignal = this.formatterState.isComplete;
  readonly isEmpty = this.formatterState.isEmpty;
  readonly shouldShowWarn = this.formatterState.shouldShowWarn;
  readonly showValidationHint = this.validationHint.showValidationHint;
  readonly dropdownOpen = this.countrySelector.dropdownOpen;
  readonly search = this.countrySelector.search;
  readonly focusedIndex = this.countrySelector.focusedIndex;
  readonly filteredCountries = this.countrySelector.filteredCountries;
  readonly hasDropdown = this.countrySelector.hasDropdown;
  readonly themeClass = this.themeState.themeClass;
  readonly copied = this.copyAction.copied;
  readonly copyAriaLabel = this.copyAction.copyAriaLabel;
  readonly copyButtonTitle = this.copyAction.copyButtonTitle;

  readonly dropdownId = ++nextDropdownId;
  readonly dropdownElementId = `pi-dropdown-${this.dropdownId}`;
  readonly listboxId = `pi-options-${this.dropdownId}`;

  readonly isDisabled = computed(() => this.disabledInput() || this.formDisabled());
  readonly isReadOnly = computed(() => this.readOnlyInput());
  readonly inactive = computed(() => this.isDisabled() || this.isReadOnly());
  readonly incomplete = computed(() => this.showValidationHint() && this.shouldShowWarn());
  readonly showCopyButton = computed(() => this.showCopy() && !this.isEmpty() && !this.isDisabled());
  readonly showClearButton = computed(() => this.showClear() && !this.isEmpty() && !this.inactive());
  readonly canOpenDropdown = computed(() => this.hasDropdown() && !this.inactive());
  readonly renderDropdown = computed(() => this.hasDropdown() && (!this.inactive() || this.dropdownOpen()));
  readonly activeOptionId = computed(() =>
    this.dropdownOpen() && this.filteredCountries()[this.focusedIndex()]
      ? this.getOptionId(this.focusedIndex())
      : undefined
  );
  readonly rootClasses = computed(() =>
    [
      'phone-input',
      `size-${this.size()}`,
      this.themeClass(),
      this.isDisabled() && 'is-disabled',
      this.isReadOnly() && 'is-readonly',
      this.disableDefaultStyles() && 'is-unstyled',
      this.withValidity() && this.incomplete() && 'is-incomplete',
      this.withValidity() && this.isCompleteSignal() && 'is-complete'
    ]
      .filter(Boolean)
      .join(' ')
  );
  readonly dropdownClasses = computed(() =>
    ['phone-dropdown', this.dropdownOpen() && 'is-open', this.dropdownClass(), this.themeClass()]
      .filter(Boolean)
      .join(' ')
  );
  readonly actionsCount = computed(
    () => +this.showCopyButton() + +this.showClearButton() + (this.actionsBeforeTemplate() ? 1 : 0)
  );

  constructor() {
    this.countryState.configure({
      country: this.countryInput,
      locale: this.localeInput,
      detect: this.detectInput,
      defaultDetect: !this.config.country,
      onCountryChange: (country) => this.countryChange.emit(country)
    });

    this.formatterState.configure({
      country: this.country,
      value: this.value,
      onChange: (digits) => this.setValue(digits, true),
      onPhoneChange: (phone) => this.phoneChange.emit(phone),
      onValidationChange: (isComplete) => this.validationChange.emit(isComplete)
    });

    this.inputHandlers.configure({
      formatter: this.formatter,
      digits: this.digits,
      inactive: this.inactive,
      onChange: (digits) => this.setValue(digits, true),
      scheduleValidationHint: (delay) => this.validationHint.scheduleValidationHint(delay)
    });

    this.countrySelector.configure({
      rootElement: () => this.rootRef()?.nativeElement,
      dropdownElement: () => this.dropdownRef()?.nativeElement,
      searchElement: () => this.searchRef()?.nativeElement,
      selectorElement: () => this.selectorRef()?.nativeElement,
      locale: this.locale,
      inactive: this.inactive,
      countryOption: this.countryInput,
      onSelectCountry: (country) => this.selectCountry(country),
      onAfterSelect: () => this.focus()
    });

    this.copyAction.configure({
      fullFormatted: this.fullFormatted,
      liveElement: () => this.liveRef()?.nativeElement,
      onCopy: (value) => this.copiedValue.emit(value)
    });

    this.themeState.configure({ theme: this.theme });

    effect((onCleanup) => {
      if (typeof document === 'undefined') return;

      const dropdown = this.dropdownRef()?.nativeElement;
      if (!dropdown || dropdown.parentElement === document.body) return;

      const placeholder = document.createComment('phone-input-dropdown');
      const parent = dropdown.parentNode;
      parent?.insertBefore(placeholder, dropdown);
      document.body.appendChild(dropdown);

      onCleanup(() => {
        if (placeholder.parentNode && dropdown.isConnected) {
          placeholder.parentNode.insertBefore(dropdown, placeholder);
        }
        placeholder.remove();
      });
    });
  }

  writeValue(value: string | number | null | undefined): void {
    this.setValue(String(value ?? ''), false);
  }

  registerOnChange(fn: (value: string) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.formDisabled.set(isDisabled);
  }

  focus(): void {
    setTimeout(() => this.telRef()?.nativeElement.focus());
  }

  blur(): void {
    this.telRef()?.nativeElement.blur();
  }

  clear(): void {
    this.setValue('', true);
    this.validationHint.clearValidationHint();
    this.cleared.emit();
  }

  selectCountry(country: CountryKey | string): boolean {
    const updated = this.countryState.setCountry(country);

    if (!updated) return false;

    const maxDigits = this.formatter().getMaxDigits();
    if (this.digits().length > maxDigits) {
      this.setValue(this.digits().slice(0, maxDigits), true);
    }

    return true;
  }

  getFullNumber(): string {
    return this.full();
  }

  getFullFormattedNumber(): string {
    return this.fullFormatted();
  }

  getDigits(): string {
    return this.digits();
  }

  isValid(): boolean {
    return this.isComplete();
  }

  isComplete(): boolean {
    return this.isCompleteSignal();
  }

  getOptionId(index: number): string {
    return `pi-option-${this.dropdownId}-${index}`;
  }

  flagContext(country: MaskFull): { $implicit: MaskFull; country: MaskFull } {
    return { $implicit: country, country };
  }

  copyContext(): { copied: boolean } {
    return { copied: this.copied() };
  }

  handleBeforeInput(event: Event): void {
    this.inputHandlers.handleBeforeInput(event);
  }

  handleInput(event: Event): void {
    this.inputHandlers.handleInput(event);
  }

  handleKeydown(event: KeyboardEvent): void {
    this.inputHandlers.handleKeydown(event);
  }

  handlePaste(event: ClipboardEvent): void {
    this.inputHandlers.handlePaste(event);
  }

  handleFocus(event: FocusEvent): void {
    this.validationHint.clearValidationHint(false);
    this.countrySelector.closeDropdown();
    this.focused.emit(event);
  }

  handleBlur(event: FocusEvent): void {
    this.onTouched();
    this.blurred.emit(event);
  }

  handleSelectorPointerDown(event: PointerEvent): void {
    this.countrySelector.handleSelectorPointerDown(event);
  }

  handleSelectorKeydown(event: KeyboardEvent): void {
    this.countrySelector.handleSelectorKeydown(event);
  }

  handleSearchChange(event: Event): void {
    this.countrySelector.handleSearchChange(event);
  }

  handleSearchKeydown(event: KeyboardEvent): void {
    this.countrySelector.handleSearchKeydown(event);
  }

  toggleDropdown(): void {
    this.countrySelector.toggleDropdown();
  }

  setFocusedIndex(index: number): void {
    this.countrySelector.setFocusedIndex(index);
  }

  selectDropdownCountry(country: CountryKey): void {
    this.countrySelector.selectCountry(country);
  }

  onClearClick(): void {
    this.clear();
    this.focus();
  }

  async onCopyClick(): Promise<void> {
    await this.copyAction.onCopyClick();
  }

  private setValue(value: string, emit: boolean): void {
    const nextDigits = extractDigits(value, this.formatter().getMaxDigits());

    untracked(() => this.value.set(nextDigits));

    if (emit) {
      this.onChange(nextDigits);
    }
  }
}

<div #root aria-label="Phone input" role="group" [class]="rootClasses()" [style.--pi-actions-count]="actionsCount()">
  <div class="pi-selector">
    <button
      #selectorButton
      type="button"
      class="pi-selector-btn"
      [class.no-dropdown]="!canOpenDropdown()"
      [disabled]="isDisabled()"
      [tabIndex]="canOpenDropdown() ? 0 : -1"
      [attr.aria-label]="'Selected country: ' + country().name"
      [attr.aria-expanded]="canOpenDropdown() ? dropdownOpen() : null"
      [attr.aria-haspopup]="canOpenDropdown() ? 'dialog' : null"
      [attr.aria-controls]="canOpenDropdown() ? dropdownElementId : null"
      (pointerdown)="handleSelectorPointerDown($event)"
      (keydown)="handleSelectorKeydown($event)"
      (click)="toggleDropdown()"
    >
      <span class="pi-flag" role="img" [attr.aria-label]="country().name + ' flag'">
        @if (flagTemplate(); as flagTpl) {
          <ng-container [ngTemplateOutlet]="flagTpl" [ngTemplateOutletContext]="flagContext(country())"></ng-container>
        } @else {
          {{ country().flag }}
        }
      </span>
      <span class="pi-code">{{ country().code }}</span>
      @if (canOpenDropdown()) {
        <svg
          class="pi-chevron"
          [class.is-open]="dropdownOpen()"
          width="12"
          height="12"
          viewBox="0 0 12 12"
          fill="none"
          aria-hidden="true"
        >
          <path
            d="M2.5 4.5L6 8L9.5 4.5"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      }
    </button>
  </div>

  <div class="pi-input-wrap">
    <input
      #telInput
      class="pi-input"
      type="tel"
      inputmode="tel"
      autocomplete="tel-national"
      autocorrect="off"
      autocapitalize="off"
      spellcheck="false"
      [id]="id()"
      [name]="name()"
      [placeholder]="displayPlaceholder()"
      [value]="displayValue()"
      [disabled]="isDisabled()"
      [readOnly]="isReadOnly()"
      [attr.aria-invalid]="incomplete()"
      (beforeinput)="handleBeforeInput($event)"
      (input)="handleInput($event)"
      (keydown)="handleKeydown($event)"
      (paste)="handlePaste($event)"
      (focus)="handleFocus($event)"
      (blur)="handleBlur($event)"
    />

    <div class="pi-actions" role="toolbar" aria-label="Phone input actions">
      @if (actionsBeforeTemplate(); as actionsTpl) {
        <ng-container [ngTemplateOutlet]="actionsTpl"></ng-container>
      }

      @if (showCopyButton()) {
        <button
          type="button"
          class="pi-btn pi-btn-copy"
          [class.is-copied]="copied()"
          [attr.aria-label]="copyAriaLabel()"
          [title]="copyButtonTitle()"
          (click)="onCopyClick()"
        >
          @if (copySvgTemplate(); as copyTpl) {
            <ng-container [ngTemplateOutlet]="copyTpl" [ngTemplateOutletContext]="copyContext()"></ng-container>
          } @else if (!copied()) {
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
              <path
                d="M13.5 5.5V13.5H5.5V5.5H13.5ZM13.5 4H5.5C4.67 4 4 4.67 4 5.5V13.5C4 14.33 4.67 15 5.5 15H13.5C14.33 15 15 14.33 15 13.5V5.5C15 4.67 14.33 4 13.5 4ZM10.5 1H2.5V11H4V2.5H10.5V1Z"
                fill="currentColor"
              />
            </svg>
          } @else {
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
              <path d="M6.5 11.5L3 8L4.06 6.94L6.5 9.38L11.94 3.94L13 5L6.5 11.5Z" fill="currentColor" />
            </svg>
          }
        </button>
      }

      @if (showClearButton()) {
        <button
          type="button"
          class="pi-btn pi-btn-clear"
          [attr.aria-label]="clearButtonLabel()"
          [title]="clearButtonLabel()"
          (click)="onClearClick()"
        >
          @if (clearSvgTemplate(); as clearTpl) {
            <ng-container [ngTemplateOutlet]="clearTpl"></ng-container>
          } @else {
            <svg width="11" height="11" viewBox="0 0 14 14" fill="none" aria-hidden="true">
              <path
                d="M14 1.41L12.59 0L7 5.59L1.41 0L0 1.41L5.59 7L0 12.59L1.41 14L7 8.41L12.59 14L14 12.59L8.41 7L14 1.41Z"
                fill="currentColor"
              />
            </svg>
          }
        </button>
      }
    </div>
  </div>
</div>

@if (renderDropdown()) {
  <div
    #dropdown
    [id]="dropdownElementId"
    [class]="dropdownClasses()"
    role="dialog"
    aria-modal="false"
    aria-label="Country"
  >
    @if (dropdownOpen()) {
      <div class="pi-search-wrap">
        <input
          #searchInput
          name="search"
          type="search"
          class="pi-search"
          aria-label="Search"
          [attr.aria-controls]="listboxId"
          [attr.aria-activedescendant]="activeOptionId()"
          [placeholder]="searchPlaceholder()"
          [value]="search()"
          (keydown)="handleSearchKeydown($event)"
          (input)="handleSearchChange($event)"
        />
      </div>
      <ul [id]="listboxId" class="pi-options" role="listbox" tabindex="-1">
        @for (c of filteredCountries(); track c.id; let idx = $index) {
          <li
            [id]="getOptionId(idx)"
            role="option"
            class="pi-option"
            tabindex="-1"
            [class.is-focused]="idx === focusedIndex()"
            [class.is-selected]="c.id === country().id"
            [attr.aria-selected]="c.id === country().id"
            [title]="c.name"
            (click)="selectDropdownCountry(c.id)"
            (keydown.enter)="selectDropdownCountry(c.id)"
            (keydown.space)="$event.preventDefault(); selectDropdownCountry(c.id)"
            (mouseenter)="setFocusedIndex(idx)"
          >
            <span class="pi-flag" role="img" [attr.aria-label]="c.name + ' flag'">
              @if (flagTemplate(); as flagTpl) {
                <ng-container [ngTemplateOutlet]="flagTpl" [ngTemplateOutletContext]="flagContext(c)"></ng-container>
              } @else {
                {{ c.flag }}
              }
            </span>
            <span class="pi-opt-name">{{ c.name }}</span>
            <span class="pi-opt-code">{{ c.code }}</span>
          </li>
        } @empty {
          <li class="pi-empty">{{ noResultsText() }}</li>
        }
      </ul>
    }
  </div>
}

<div #live class="sr-only" role="status" aria-live="polite" aria-atomic="true"></div>

// packages/phone-mask-svelte/src/components/PhoneInput.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte';
  import { useCountry } from '../composables/internal/useCountry.svelte';
  import { useFormatter } from '../composables/internal/useFormatter.svelte';
  import { useValidationHint } from '../composables/internal/useValidationHint.svelte';
  import { useInputHandlers } from '../composables/internal/useInputHandlers.svelte';
  import { useCountrySelector } from '../composables/internal/useCountrySelector.svelte';
  import { useCopyAction } from '../composables/internal/useCopyAction.svelte';
  import { useTheme } from '../composables/internal/useTheme.svelte';

  import type { PhoneInputProps } from '../types';

  let {
    value = $bindable(''),
    id,
    name,
    country: propCountry,
    detect = true,
    locale: propLocale,
    size = 'normal',
    theme = 'auto',
    disabled = false,
    readonly = false,
    showCopy = true,
    showClear = false,
    withValidity = true,
    searchPlaceholder = 'Search country or code...',
    noResultsText = 'No countries found',
    clearButtonLabel = 'Clear phone number',
    dropdownClass = '',
    disableDefaultStyles = false,
    onchange,
    oncountrychange,
    onvalidationchange,
    onfocus,
    onblur,
    oncopy,
    onclear,
    flag,
    copysvg,
    clearsvg,
    actionsbefore,
    class: extraClass,
    ...restProps
  }: PhoneInputProps = $props();

  // --- Refs ---
  let rootEl = $state<HTMLDivElement | null>(null);
  let telEl = $state<HTMLInputElement | null>(null);
  let liveEl = $state<HTMLDivElement | null>(null);
  let dropdownEl = $state<HTMLDivElement | null>(null);
  let searchEl = $state<HTMLInputElement | null>(null);
  let selectorEl = $state<HTMLButtonElement | null>(null);

  // --- Composables (keep as objects to preserve reactive getter chains) ---
  const countryData = useCountry({
    country: () => propCountry,
    locale: () => propLocale,
    detect: () => detect,
    onCountryChange: (...args) => oncountrychange?.(...args)
  });

  const formatterData = useFormatter({
    country: () => countryData.country,
    value: () => value,
    onChange: (v) => (value = v),
    onPhoneChange: (...args) => onchange?.(...args),
    onValidationChange: (...args) => onvalidationchange?.(...args)
  });

  const validationHint = useValidationHint();

  const inactive = $derived(disabled || readonly);
  const incomplete = $derived(validationHint.showValidationHint && formatterData.shouldShowWarn);
  const showCopyButton = $derived(showCopy && !formatterData.isEmpty && !disabled);
  const showClearButton = $derived(showClear && !formatterData.isEmpty && !inactive);

  const copyData = useCopyAction({
    liveRef: () => liveEl,
    fullFormatted: () => formatterData.fullFormatted,
    onCopy: (...args) => oncopy?.(...args)
  });

  const focusInput = () => tick().then(() => telEl?.focus());

  const selectorData = useCountrySelector({
    rootRef: () => rootEl,
    dropdownRef: () => dropdownEl,
    searchRef: () => searchEl,
    selectorRef: () => selectorEl,
    locale: () => countryData.locale,
    countryOption: () => propCountry,
    inactive: () => inactive,
    onSelectCountry: countryData.setCountry,
    onAfterSelect: focusInput
  });
  let dropdownId = $state<string>('0'); // Migrate to $props.id() once we stop supporting Svelte < 5.20.0
  onMount(() => {
    dropdownId = Math.random().toString(36).slice(2, 10);
  });
  const listboxId = $derived(`pi-options-${dropdownId}`);
  const dropdownElementId = $derived(`pi-dropdown-${dropdownId}`);
  const getOptionId = (idx: number) => `pi-option-${dropdownId}-${idx}`;
  const activeOptionId = $derived(
    selectorData.dropdownOpen && selectorData.filteredCountries[selectorData.focusedIndex]
      ? getOptionId(selectorData.focusedIndex)
      : undefined
  );

  const inputHandlers = useInputHandlers({
    formatter: () => formatterData.formatter,
    digits: () => formatterData.digits,
    inactive: () => inactive,
    onChange: (v) => (value = v),
    scheduleValidationHint: validationHint.scheduleValidationHint
  });

  const handleFocus = (e: FocusEvent) => {
    validationHint.clearValidationHint(false);
    selectorData.closeDropdown();
    onfocus?.(e);
  };

  const handleBlur = (e: FocusEvent) => onblur?.(e);

  export function focus() {
    focusInput();
  }
  export function blur() {
    telEl?.blur();
  }
  export function clear() {
    value = '';
    validationHint.clearValidationHint();
    onclear?.();
  }
  export function selectCountry(code?: string | null) {
    countryData.setCountry(code);
  }
  export function getFullNumber() {
    return formatterData.full;
  }
  export function getFullFormattedNumber() {
    return formatterData.fullFormatted;
  }
  export function getDigits() {
    return formatterData.digits;
  }
  export function isValid() {
    return formatterData.isComplete;
  }
  export function isComplete() {
    return formatterData.isComplete;
  }

  const handleClearClick = () => {
    clear();
    focusInput();
  };

  const themeData = useTheme({
    theme: () => theme
  });

  const rootClasses = $derived(
    [
      'phone-input',
      `size-${size}`,
      themeData.themeClass,
      disabled && 'is-disabled',
      readonly && 'is-readonly',
      disableDefaultStyles && 'is-unstyled',
      withValidity && incomplete && 'is-incomplete',
      withValidity && formatterData.isComplete && 'is-complete',
      extraClass
    ]
      .filter(Boolean)
      .join(' ')
  );

  const actionsCount = $derived(+showCopyButton + +showClearButton + (actionsbefore ? 1 : 0));
  const canOpenDropdown = $derived(selectorData.hasDropdown && !inactive);
  const renderDropdown = $derived(selectorData.hasDropdown && (!inactive || selectorData.dropdownOpen));

  const portalToBody = (node: HTMLElement) => {
    document.body.appendChild(node);
    return { destroy: () => node.remove() };
  };
</script>

<div
  bind:this={rootEl}
  class={rootClasses}
  {...restProps}
  data-desource-phone-mask="input"
  style:--pi-actions-count={actionsCount}
  role="group"
  aria-label="Phone input"
>
  <!-- Country Selector -->
  <div class="pi-selector">
    <button
      bind:this={selectorEl}
      type="button"
      class="pi-selector-btn"
      class:no-dropdown={!canOpenDropdown}
      {disabled}
      tabindex={canOpenDropdown ? undefined : -1}
      aria-label="Selected country: {countryData.country.name}"
      aria-expanded={canOpenDropdown && selectorData.dropdownOpen}
      aria-haspopup={canOpenDropdown ? 'dialog' : undefined}
      aria-controls={canOpenDropdown ? dropdownElementId : undefined}
      onpointerdown={selectorData.handleSelectorPointerDown}
      onkeydown={selectorData.handleSelectorKeydown}
      onclick={selectorData.toggleDropdown}
    >
      <span class="pi-flag" role="img" aria-label="{countryData.country.name} flag">
        {#if flag}{@render flag(countryData.country)}{:else}{countryData.country.flag}{/if}
      </span>
      <span class="pi-code">{countryData.country.code}</span>
      {#if canOpenDropdown}
        <svg
          class="pi-chevron"
          class:is-open={selectorData.dropdownOpen}
          width="12"
          height="12"
          viewBox="0 0 12 12"
          fill="none"
          aria-hidden="true"
        >
          <path
            d="M2.5 4.5L6 8L9.5 4.5"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      {/if}
    </button>
  </div>

  <!-- Input -->
  <div class="pi-input-wrap">
    <input
      bind:this={telEl}
      type="tel"
      inputmode="tel"
      {id}
      {name}
      autocomplete="tel-national"
      autocorrect="off"
      autocapitalize="off"
      spellcheck="false"
      class="pi-input"
      placeholder={formatterData.displayPlaceholder}
      value={formatterData.displayValue}
      {disabled}
      {readonly}
      aria-invalid={incomplete}
      onbeforeinput={inputHandlers.handleBeforeInput}
      oninput={inputHandlers.handleInput}
      onkeydown={inputHandlers.handleKeydown}
      onpaste={inputHandlers.handlePaste}
      onfocus={handleFocus}
      onblur={handleBlur}
    />

    <!-- Actions -->
    <div class="pi-actions" role="toolbar" aria-label="Phone input actions">
      {#if actionsbefore}
        {@render actionsbefore()}
      {/if}

      {#if showCopyButton}
        <button
          type="button"
          class="pi-btn pi-btn-copy"
          class:is-copied={copyData.copied}
          aria-label={copyData.copyAriaLabel}
          title={copyData.copyButtonTitle}
          onclick={copyData.onCopyClick}
        >
          {#if copysvg}
            {@render copysvg(copyData.copied)}
          {:else if copyData.copied}
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
              <path d="M6.5 11.5L3 8L4.06 6.94L6.5 9.38L11.94 3.94L13 5L6.5 11.5Z" fill="currentColor" />
            </svg>
          {:else}
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
              <path
                d="M13.5 5.5V13.5H5.5V5.5H13.5ZM13.5 4H5.5C4.67 4 4 4.67 4 5.5V13.5C4 14.33 4.67 15 5.5 15H13.5C14.33 15 15 14.33 15 13.5V5.5C15 4.67 14.33 4 13.5 4ZM10.5 1H2.5V11H4V2.5H10.5V1Z"
                fill="currentColor"
              />
            </svg>
          {/if}
        </button>
      {/if}

      {#if showClearButton}
        <button
          type="button"
          class="pi-btn pi-btn-clear"
          aria-label={clearButtonLabel}
          title={clearButtonLabel}
          onclick={handleClearClick}
        >
          {#if clearsvg}
            {@render clearsvg()}
          {:else}
            <svg width="11" height="11" viewBox="0 0 14 14" fill="none" aria-hidden="true">
              <path
                d="M14 1.41L12.59 0L7 5.59L1.41 0L0 1.41L5.59 7L0 12.59L1.41 14L7 8.41L12.59 14L14 12.59L8.41 7L14 1.41Z"
                fill="currentColor"
              />
            </svg>
          {/if}
        </button>
      {/if}
    </div>
  </div>

  <!-- Dropdown -->
  {#if renderDropdown}
    <div
      id={dropdownElementId}
      bind:this={dropdownEl}
      use:portalToBody
      class="phone-dropdown {dropdownClass} {themeData.themeClass}"
      class:is-open={selectorData.dropdownOpen}
      class:is-unstyled={disableDefaultStyles}
      data-desource-phone-mask="dropdown"
      role="dialog"
      aria-modal="false"
      aria-label="Country"
    >
      {#if selectorData.dropdownOpen}
        <div class="pi-search-wrap">
          <input
            bind:this={searchEl}
            name="search"
            type="search"
            class="pi-search"
            aria-label="Search"
            placeholder={searchPlaceholder}
            aria-controls={listboxId}
            aria-activedescendant={activeOptionId}
            value={selectorData.search}
            onkeydown={selectorData.handleSearchKeydown}
            oninput={selectorData.handleSearchChange}
          />
        </div>
        <ul id={listboxId} class="pi-options" role="listbox" tabindex="-1">
          {#each selectorData.filteredCountries as c, idx (c.id)}
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <li
              id={getOptionId(idx)}
              role="option"
              class="pi-option"
              class:is-focused={idx === selectorData.focusedIndex}
              class:is-selected={c.id === countryData.country.id}
              aria-selected={c.id === countryData.country.id}
              title={c.name}
              onclick={() => selectorData.selectCountry(c.id)}
              onmouseenter={() => selectorData.setFocusedIndex(idx)}
            >
              <span class="pi-flag" role="img" aria-label="{c.name} flag">
                {#if flag}{@render flag(c)}{:else}{c.flag}{/if}
              </span>
              <span class="pi-opt-name">{c.name}</span>
              <span class="pi-opt-code">{c.code}</span>
            </li>
          {:else}
            <li class="pi-empty">{noResultsText}</li>
          {/each}
        </ul>
      {/if}
    </div>
  {/if}

  <!-- Screen reader live region -->
  <div bind:this={liveEl} class="sr-only" role="status" aria-live="polite" aria-atomic="true"></div>
</div>
